baseURL = "https://egazzarr.github.io/portfolio/"
#baseURL = "https://egazzarr.github.io"
#baseURL = "https://example.org/"
#baseURL = "https://localhost:42105/"
languageCode = "en-us"
title = "Elena Gazzarrini"
# theme = "sourgough-starter"
#relativeURLs = true
#uglyURLs = true

publishDir = "docs"

[markup.goldmark.renderer]
    unsafe= true

[params]
#------------- Config -------------------
    scholarLink = false
    scopusLink = false
    dimensionsLink = false
    dimensionCitations = false
    backgroundPath = "images/estate/mountain.jpg"
    googleScholar = 'XXXX' # These are needed only if set to true above
    scopusID = 'XXXX'
    dimensionsID = 'XXXX'
    footerOffset = -60

#-------------- Defined ------------
    css= ["css/sourgough.css"]

[menu]

  [[menu.main]]
    identifier = "estate"
    name = "estate"
    url = "/estate/"

  [[menu.main]]
    identifier = "color"
    name = "color"
    url = "/color/"

  [[menu.main]]
    identifier = "slab_city"
    name = "slab_city"
    url = "/slab_city/"

  [[menu.main]]
    identifier = "bw"
    name = "b+w"
    url = "/bw/"

  [[menu.main]]
    identifier = "p5"
    name = "p5"
    url = "/p5/"

  [[menu.main]]
  identifier = "dual"
  name = "dual"
  url = "/dual/"

  [[menu.main]]
  identifier = "ceramica"
  name = "ceramica"
  url = "/ceramica/"

  [[menu.main]]
  identifier = "triad"
  name = "triad"
  url = "/triad/"

  [[menu.main]]
  identifier = "kids"
  name = "kids"
  url = "/kids/"

  [[menu.main]]
  identifier = "blues"
  name = "blues"
  url = "/blues/"

#  [[menu.main]]
 # identifier = "portrait"
  #name = "portrait"
  #url = "/portrait/"

#----- NavBottom Links ------
 [[menu.bot]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/egazzarr/"
    pre = "fab fa-github"

 [[menu.bot]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/egazzarrini/"
    pre = "fab fa-linkedin-in"

 [[menu.bot]]
    identifier = "yt"
    name = "YouTube"
    url = "https://www.youtube.com/@elenagazzarrini7572/videos"
    pre = "fab fa-youtube"

#-------- About section links ----- 
#  [[menu.about]]
  #  identifier = "ordcidid"
   # name = "OrcidID"
   # url = ""
    #pre = "fab fa-orcid"

#----------- Text Links -------
  [[menu.link]]
    identifier = "email"
    name = "e-mail"
    url = "mailto:gazzarrini.elena@gmail.com"

 [[menu.link]]
    identifier = "resume"
    name = "CV"
    url = "/cv/"

 [[menu.link]]
    identifier = "about"
    name = "about"
    url = "/about/"

 #[[menu.link]]
 #  identifier = "MindMap"
 #  name = "MindMap"
 #  url = "/mindmap/"

[taxonomies]
  authors = "authors"

  #[[menu.link]]
   # identifier = "github"
   # name = "git"
   # url = "https://github.com/egazzarr/"
   # pre = "fab fa-github"
   
  #[[menu.link]]
   # identifier = "linkedin"
   # name = "LinkedIn"
   # url = "https://www.linkedin.com/in/egazzarrini/"
  
