baseURL = "https://egazzarr.github.io/"
# baseURL = "http://example.org/"
languageCode = "en-us"
title = "Elena Gazzarrini"
theme = "sourgough-starter"
relativeURLs = true
uglyURLs = true

# publishDir = "docs"

[markup.goldmark.renderer]
    unsafe= true

[params]
#------------- Config -------------------
    scholarLink = false
    scopusLink = false
    dimensionsLink = false
    dimensionCitations = false
    backgroundPath = "images/estate/mountain.JPG"
    googleScholar = 'XXXX' # These are needed only if set to true above
    scopusID = 'XXXX'
    dimensionsID = 'XXXX'
    footerOffset = -60

#-------------- Defined ------------
    css= ["css/sourgough.css"]

[menu]
#----- Navbar links ------

 # [[menu.main]]
  #  identifier = "publications"
   # name = "Publications"
   # url = "/publications/"

  [[menu.main]]
    identifier = "estate"
    name = "estate"
    url = "https://egazzarr.github.io/portfolio/estate/"

  [[menu.main]]
    identifier = "color"
    name = "color"
    url = "https://egazzarr.github.io/portfolio/color/"

  [[menu.main]]
    identifier = "slab_city"
    name = "slab_city"
    url = "https://egazzarr.github.io/portfolio/slab_city/"

  [[menu.main]]
    identifier = "bw"
    name = "b+w"
    url = "https://egazzarr.github.io/portfolio/bw/"

  [[menu.main]]
    identifier = "p5"
    name = "p5"
    url = "https://egazzarr.github.io/portfolio/p5/"

    [[menu.main]]
    identifier = "dual"
    name = "dual"
    url = "https://egazzarr.github.io/portfolio/dual/"

    [[menu.main]]
    identifier = "ceramica"
    name = "ceramica"
    url = "https://egazzarr.github.io/portfolio/ceramica/"

 # [[menu.main]]
 #   identifier = "manifesto"
 #   name = "manifesto"
 #   url = "https://egazzarr.github.io/portfolio/about/"

#----- NavBottom Links ------
 [[menu.bot]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/egazzarr/"
    pre = "fab fa-github"

#  [[menu.bot]]
 #   identifier = "gitlab"
  #  name = "Gitlab"
   # url = "https://gitlab.com/jack-alope/"
    # pre = "fab fa-gitlab"

 [[menu.bot]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/egazzarrini/"
    pre = "fab fa-linkedin-in"

#-------- About section links ----- 
#  [[menu.about]]
  #  identifier = "ordcidid"
   # name = "OrcidID"
   # url = ""
    #pre = "fab fa-orcid"

  #[[menu.about]]
  #  identifier = "researchgate"
 #   name = "ResearchGate"
 #   url = ""
  #  pre = "fab fa-researchgate"

  #[[menu.about]]
   # identifier = "medium"
  #  name = "Medium"
  #  url = ""
    #pre = "fab fa-medium-m"

  #[[menu.about]]
   # identifier = "googlescholar"
   # name = "Google Scholar"
   # url = ""
  #  pre = "fas fa-graduation-cap"

#----------- Text Links -------
  [[menu.link]]
    identifier = "email"
    name = "e-mail"
    url = "mailto:gazzarrini.elena@gmail.com"

 [[menu.link]]
    identifier = "resume"
    name = "CV"
    url = "https://egazzarr.github.io/portfolio/cv/"

#[[menu.link]]
 #   identifier = "MindMap"
  #  name = "MindMap"
   # url = "https://egazzarr.github.io/portfolio/mindmap/"

[taxonomies]
  authors = "authors"

  #[[menu.link]]
   # identifier = "github"
   # name = "git"
   # url = "https://github.com/egazzarr/"
   # pre = "fab fa-github"
   

  #[[menu.link]]
   # identifier = "linkedin"
   # name = "LinkedIn"
   # url = "https://www.linkedin.com/in/egazzarrini/"
  
